DROP TABLE IF EXISTS users;

CREATE TABLE USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    activation_code VARCHAR (100),
    username VARCHAR (100),
    email VARCHAR (250) UNIQUE NOT NULL,
    password VARCHAR (250) NOT NULL,
    role VARCHAR (250) NOT NULL,
    enabled INT NOT NULL DEFAULT 0,
    created TIMESTAMP,
    deleted INT NOT NULL DEFAULT 0
);

CREATE TABLE VARIABLES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    key VARCHAR (100) NOT NULL,
    value VARCHAR (100) NOT NULL,
    user_id INT NOT NULL,
    type VARCHAR(10) NOT NULL,
    created TIMESTAMP,
    updated TIMESTAMP
);

CREATE TABLE SYSTEM_VARIABLES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    key VARCHAR (100) NOT NULL,
    value VARCHAR (100) NOT NULL,
    type VARCHAR(10) NOT NULL,
    created TIMESTAMP
)

CREATE TABLE DOCKER_NODES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    node VARCHAR (20) NOT NULL,
    status VARCHAR (20) NOT NULL,
    user_id INT NOT NULL,
    created TIMESTAMP
)

CREATE TABLE NODE_LOGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    level VARCHAR (10) NOT NULL,
    category VARCHAR (10) NOT NULL,
    log TEXT,
    node_id INT NOT NULL,
    created TIMESTAMP
)

CREATE TABLE SYSTEM_LOGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    level VARCHAR (10) NOT NULL,
    category VARCHAR (10) NOT NULL,
    created TIMESTAMP,
    log TEXT
)

ALTER TABLE VARIABLES
    ADD CONSTRAINT USER_FK
    FOREIGN KEY (user_id)
    REFERENCES USERS(id);

ALTER TABLE DOCKER_NODES
    ADD CONSTRAINT NODE_FK
    FOREIGN KEY (user_id)
    REFERENCES USERS(id)

ALTER TABLE NODE_LOGS
    ADD CONSTRAINT LOG_FK
    FOREIGN KEY (node_id)
    REFERENCES DOCKER_NODES(id)

INSERT INTO VARIABLE_DATA_TYPES (value) VALUES ('text')
INSERT INTO VARIABLE_DATA_TYPES (value) VALUES ('password')

INSERT INTO SYSTEM_VARIABLES (key, value) VALUES ('E2E_BASE_URL', 'https://nlbavwidm3.infor.com/infor')
INSERT INTO SYSTEM_VARIABLES (key, value) VALUES ('E2E_ENVIRONMENT', 'staging')
INSERT INTO SYSTEM_VARIABLES (key, value) VALUES ('E2E_DOCUMENT_TYPE', 'Automation')
INSERT INTO SYSTEM_VARIABLES (key, value) VALUES ('E2E_FILE_PATH', '/home/gradle/app/1.jpg')
INSERT INTO SYSTEM_VARIABLES (key, value) VALUES ('E2E_USER', 'irdcmfiladm@infor.com')
INSERT INTO SYSTEM_VARIABLES (key, value) VALUES ('E2E_PASSWORD', 'Tequila12')