version: "3.5"
networks:
  e2e-nw:
    driver: bridge
    name: e2e-nw
services:
  hub:
    image: selenium/hub:3.141.59-vanadium
    networks:
      - e2e-nw
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_TIMEOUT=3000
      - GRID_BROWSER_TIMEOUT=0

docker network create --driver bridge e2e-network
docker run --name selenium-hub --network=e2e-network -p 8888:4444 -e GRID_TIMEOUT=3000 -e GRID_BROWSER_TIMEOUT=0 -d selenium/hub:3.141.59-vanadium