version: "3.5"
networks:
  e2e-nw:
    driver: bridge
    name: e2e-nw
services:
  chrome-1:
    image: selenium/node-chrome:3.141.59-vanadium
    networks:
      - e2e-nw
    container_name: chrome-1
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=32
  e2e-chrome-1:
    image: e2e-1
    networks:
      - e2e-nw
    container_name: e2e-node-1
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

docker run --name chrome-<random number> --network=e2e-network -v /dev/shm:/dev/shm -e HUB_HOST=selenium-hub
  -e HUB_PORT=4444 -e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1080 -e SCREEN_DEPTH=32 -d selenium/node-chrome:3.141.59-vanadium

docker run --name e2e-node-1 --network=e2e-network -v $(pwd):/home/gradle/app/build/reports/ -e HUB_HOST=hub -e HUB_PORT=4444 -d e2e-1